### ISSUE TITLE
Licence missing

### ISSUE THREAD

**Issue by dddejan** [meelgroup/arjun#5]
I came to the repo following dependencies: unigen -> approxmc -> arjun

All other tools are MIT, can you please provide a LICENCE file to clarify.

**Comment by msoos** [comment]
Hi,

Thanks, good point! Sorry for missing it. However, please note that all
files should have an MIT header, which should clarify things. Also the
GitHub page should show MIT license as selected. I'll double check, just to
be sure, and add the LICENSE file.

Thanks again,

Mate

**Comment by msoos** [comment]
Oops GitHub license is not set, and one file (not compiled into the
executable, the example.cpp) is missing the header. Good catch!

Mate

**Comment by msoos** [comment]
Hi!

First of all, thanks again for spotting this! I have now fixed the issue with bb2abdca0d53202cec3b9e01a1166f570f72f121. This adds the LICENSE file and it adds the required header to `example.cpp`.

Please note that *all* code required to build the executable, including code to build the code (i.e. cmake files) were all clearly, individually MIT licensed (except for Mersenne Twister, which is clearly, individually marked as BSD, essentially MIT compatible). Hence, while it is _very_ important to have a LICENSE file, and it was a mistake not to have it, it was always absolutely legal to use the tool under MIT license, since each file was individually, and clearly, licensed that way.

I hope the above helps. I am closing the issue because I believe this fixes the underlying issue. Please let me know if that's not OK.

Thanks again,

Mate

**Comment by dddejan** [comment]
Thanks! Makes it easier to convey the licensing to tools and lawyers :)
